$(document).ready(function(){
	select(1);
	PRouter.route('/tab/:num', function(num){
		select(num);
	});
	PRouter.queryRoute('loc', function(value){
		scrollTo(value);
	});
	PRouter.start();
	$('.tab').click(function(){
		PRouter.push('/tab/' + this.id.substring(3));
	});
	window.cat = new Catalog('page1');
	$('#catalog').append(cat.genCatalog());
	cat.each(function(row, children, target, index){
		row.onclick = function() {
			PRouter.push('?loc=' + (target.offsetTop - 81));
		}
	})
});
var scrollTop = {};
var selected;
function _(id){
	return document.getElementById(id);
}
function scrollTo(loc, old){
	var top = isNaN(loc) ? (_(loc).offsetTop - 81) || 0 : loc;
	var n = selected || 1;
	var id = 'page' + n;
	var element = _(id) || document.body;
	var oldTop = element.scrollTop;
	var speed = parseInt(Math.abs(element.scrollTop - top) / 20);
	if (element.scrollTop == top || element.scrollTop == old) return false;
	element.scrollTop += element.scrollTop < top ? speed : -speed;
	setTimeout(function(){scrollTo(top, oldTop)}, 1);
}
function select(count){
	var n = count || 1;
	_('container').style.left = 100 * (1 - n) + '%';
	scrollTop[n] = scrollTop[n] || 0;
	if (selected) {
		scrollTop[selected] = _('page' + selected).scrollTop;
		_('page' + selected).style.overflowY = 'hidden';
		_('tab' + selected).className = 'tab';
		setTimeout(function(){
			_('page' + n).style.overflowY = 'auto';
		}, 500);
	}else{
		setTimeout(function(){
			_('container').className += ' animation';
		}, 1);
	}
	
	_('tab' + n).className += ' selected';
	selected = n;
}
// Generated by CoffeeScript 1.7.1
var Catalog;

Catalog = (function() {
  function Catalog(mainId) {
    this.mainId = mainId;
  }

  Catalog.prototype.genCatalog = function() {
    var catAnchorNode, catNode, child, children, content, range, rootDiv, stack, subCat, _i, _len;
    content = document.getElementById(this.mainId);
    children = content.querySelectorAll('h1, h2, h3, h4, h5, h6');
    rootDiv = document.createElement('div');
    this.nodeArr = [rootDiv];
    this.targetArr = [rootDiv];

    stack = [
      {
        node: 0,
        range: 0
      }
    ];
    for (_i = 0, _len = children.length; _i < _len; _i++) {
      child = children[_i];
      this.targetArr.push(child);
      range = parseInt(child.tagName.substr(1));
      catNode = document.createElement('li');
      catAnchorNode = document.createElement('a');
      catAnchorNode.innerHTML = child.innerHTML;
      catNode.appendChild(catAnchorNode);
      this.nodeArr.push(catNode);
      if (range === stack[stack.length - 1].range) {
        stack.pop();
      } else if (range < stack[stack.length - 1].range) {
        while (range <= stack[stack.length - 1].range) {
          stack.pop();
        }
      } else {
        subCat = document.createElement('ul');
        this.nodeArr[stack[stack.length - 1].node].appendChild(subCat);
      }
      stack.push({
        node: this.nodeArr.length - 1,
        range: range
      });
      this.nodeArr[stack[stack.length - 2].node].lastChild.appendChild(catNode);
    }
    return this.nodeArr[0].firstChild;
  };

  Catalog.prototype.each = function(fn) {
    var targetArr;
    targetArr = this.targetArr;
    return this.nodeArr.forEach(function(node, index, Arr) {
      if (index !== 0) {
        return fn(node.firstChild, node.childNodes[1], targetArr[index], index - 1);
      }
    });
  };

  return Catalog;

})();


function runDemmo(demoCode){
	var code = demoCode || '';
	var inner = '<!DOCTYPE html>\
	<html>\
	<head>\
	<title>Demo</title>\
	<meta charset="utf-8" />\
	<link rel="stylesheet" href="css/googlecode.css">\
	<style>\
	body{background:#333}\
	a,a:link,a:visited{text-decoration: underline;cursor: pointer;color: #276677;}\
	.main{margin:0 auto;width:1050px;}\
	textarea,.show{font-family:mon-space;float:left;margin:10px;border:0;width:1000px;height:300px;background:#fff;}\
	</style>\
	</head>\
	<body>\
	<div class="main">\
		<textarea readonly="readonly">' + code +
		'</textarea>\
		<div class="show">' + code + '\
		</div>\
	</div>\
	</body>\
	</html>'
	var openWindow = window.open();
	openWindow.document.write(inner);
}
$('#demo1').click(function(){
	var code = '\
<!DOCTYPE html>\n\
<html>\n\
<head>\n\
</head>\n\
<body>\n\
	<button id="button1" onclick="PRouter.push(\'/demo/1-1\')">demo 1-1</button>\n\
	<button id="button2" onclick="PRouter.push(\'/demo/1-2\')">demo 1-2</button>\n\
	<div id="container"></div>\n\
	<script src="prouter.js"></script>\n\
	<script>\n\
	// 当 "/demo/:num" 出现在 URL 中或 `num` 的值改变时回调函数就会被执行, 同时 `num` 将作为函数参数.\n\
	PRouter.route(\'/demo/:num\', function(num){\n\
		document.getElementById(\'container\').innerHTML = \'This is demo \' + num;\n\
	});\n\
\n\
	// 启动 PRouter.\n\
	PRouter.start();\n\
	</script>\n\
</body>\n\
</html>';
	runDemmo(code);
});
$('#demo2').click(function(){
	var code = '\
<!DOCTYPE html>\n\
<html>\n\
</head>\n\
<body>\n\
	<a href="/demo/2-1" href-opt="push">demo 2-1</a>\n\
	<a href="/demo/2-2" href-opt="push">demo 2-2</a>\n\
	<div id="container"></div>\n\
	<script src="prouter.js"></script>\n\
	<script>\n\
	// 当 "/demo/:num" 出现在 URL 中或 `num` 的值改变时回调函数就会被执行, 同时 `num` 将作为函数参数.\n\
	PRouter.route(\'/demo/:num\', function(num){\n\
		document.getElementById(\'container\').innerHTML = \'This is demo \' + num;\n\
	});\n\
	\n\
	// 向所有有 `href-opt` 属性的 `a` 元素绑定点击事件.\n\
	PRouter.bindForTag();\n\
	\n\
	// 启动 PRouter.\n\
	PRouter.start();\n\
	</script>\n\
</body>\n\
</html>';
	runDemmo(code);
});